// This class is Auto-Generated by the Script Tool in the Language Source
using UnityEngine;

namespace I2.Loc
{
	public static class ScriptLocalization
	{
		public static string Get( string Term, bool FixForRTL = false, int maxLineLengthForRTL = 0 ) { return LocalizationManager.GetTermTranslation(Term, FixForRTL, maxLineLengthForRTL); }


		public static string bye 		{ get{ return Get ("bye"); } }
		public static string hi 		{ get{ return Get ("hi"); } }

	}
}
